import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Nool Topluluk Kuralları | Drective', description: 'Nool topluluk kuralları, içerik şikayeti ve kullanıcı sorumlulukları.' };
export default function NoolTerms() {
  return <main className="min-h-screen bg-[#0a0a0c] px-6 pb-24 pt-32 text-gray-200"><article className="mx-auto max-w-3xl space-y-7 leading-relaxed">
    <a className="text-amber-300 underline" href="/nool">← Nool destek</a><h1 className="text-4xl font-bold text-amber-400">Nool topluluk kuralları ve kullanım koşulları</h1><p>Son güncelleme: 8 Ekim 2026. Yayıncı: Efe Arda Arıç.</p>
    <section><h2 className="mb-3 text-2xl font-semibold">Güvenli paylaşım</h2><p>Yasadışı içerik, cinsel istismar, çıplaklık, nefret söylemi, taciz, zorbalık, tehdit, kişisel bilgilerin izinsiz paylaşılması ve başkalarının haklarını ihlal eden içerikler yasaktır. Bu içeriklere tolerans gösterilmez. Yalnızca paylaşma hakkına sahip olduğunuz içerikleri yükleyin; başkalarının gizliliğine saygı gösterin.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Şikayet ve yaptırımlar</h2><p>Uygunsuz videoları video menüsünden bildirin ve istenmeyen kullanıcıları engelleyin. Şikayetler incelenebilir; içerikler kaldırılabilir ve kuralları ihlal eden hesapların erişimi kısıtlanabilir. Daha fazla bilgi veya bir şikayet için <a className="underline" href="mailto:aricefearda@gmail.com">aricefearda@gmail.com</a> adresine yazın.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Hesap, yaş ve gizlilik</h2><p>Hesap bilgilerinizin doğruluğundan, hesabınızın güvenliğinden ve paylaştığınız içerikten sorumlusunuz. Bulunduğunuz yerde hizmeti kullanmak için gerekli yasal yaş şartlarını karşılamalısınız. Gerekli izinleri vermediğinizde ilgili özellikler sınırlanabilir. Hesap silme işlemi Profil → Ayarlar → Hesabı sil bölümünde bulunur.</p><p className="mt-3"><a className="text-amber-300 underline" href="/nool/privacy">Nool gizlilik politikası</a> işlenen verileri, hizmet sağlayıcılarını ve veri taleplerini açıklar.</p></section>
    <section lang="en"><h2 className="mb-3 text-2xl font-semibold">Community rules</h2><p>Illegal content, sexual exploitation, nudity, hate speech, harassment, bullying, threats and unauthorized disclosure of personal information are prohibited. Share only content you have the right to share. Report inappropriate videos and block unwanted users from the video menu. Content may be removed and violating accounts may be restricted. Contact aricefearda@gmail.com for support and reports.</p></section>
    <p><a className="text-amber-300 underline" href="https://drective.io">https://drective.io</a></p>
  </article></main>;
}
