import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Nool Gizlilik Politikası | Drective', description: 'Nool hesap, konum, video, mesaj ve bildirim verilerinin kullanımı.' };
export default function NoolPrivacy() {
  return <main className="min-h-screen bg-[#0a0a0c] px-6 pb-24 pt-32 text-gray-200"><article className="mx-auto max-w-3xl space-y-7 leading-relaxed">
    <a className="text-amber-300 underline" href="/nool">← Nool destek / Support</a><h1 className="text-4xl font-bold text-amber-400">Nool gizlilik politikası</h1><p>Son güncelleme: 8 Ekim 2026. Bu metin Nool mobil uygulamasını kapsar. Yayıncı: Efe Arda Arıç. İletişim: <a className="underline" href="mailto:aricefearda@gmail.com">aricefearda@gmail.com</a>.</p>
    <section><h2 className="mb-3 text-2xl font-semibold">İşlediğimiz bilgiler</h2><p>Hesap oluşturduğunuzda e-posta adresi, hesap kimliği, kullanıcı adı ve seçtiğiniz profil bilgileri işlenir. Google veya Apple ile giriş seçerseniz bu sağlayıcıların paylaştığı kimlik bilgileri kullanılır. Üniversite e-postası ve alan adı, kampüs üyeliği için kullanılabilir.</p><p className="mt-3">Paylaştığınız videolar, videoların sesi, profil fotoğrafları, yorumlar, tepkiler, arkadaşlık ilişkileri, grup üyelikleri, mesajlar ve içerik şikayetleri sunucuda işlenir. Hesap ve içerikler hesap kimliğiyle ilişkilendirilebilir. Yerel cihaz kimliği ve tercihler cihazınızda saklanır.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Konum ve cihaz izinleri</h2><p>İzin verirseniz kesin konumunuz yakındaki içerikleri sıralamak ve paylaşılan videonun konumunu belirlemek için kullanılır. Konum vermeden uygulamaya devam edebilirsiniz; yakınlık özellikleri sınırlanır. Kamera ve mikrofon video kaydı için, fotoğraf erişimi seçtiğiniz profil görseli için kullanılır. İzinleri cihaz ayarlarından kapatabilirsiniz.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Paylaşım ve hizmet sağlayıcıları</h2><p>Herkese açık videolar ve profil bilgileri diğer kullanıcılara gösterilir. Kampüs ve grup içerikleri ilgili erişim kurallarına tabidir. Alıcılar gördükleri içerikleri kaydedebilir; paylaşımlarınıza hassas bilgiler eklemeyin.</p><p className="mt-3">Kimlik doğrulama, veritabanı ve dosya saklama için Supabase; etkinleştirildiğinde bildirimler için Firebase Cloud Messaging kullanılır. Bildirim hizmeti cihaz bildirim belirtecini işleyebilir. Harita ve yazı tipi hizmetleri ağ istekleri sırasında IP adresinizi görebilir. Hizmet sağlayıcıların altyapısına bağlı olarak veriler ülkeniz dışında işlenebilir. Nool uygulama içinde reklam takibi amacıyla veri toplamaz.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Saklama ve silme</h2><p>Video akışındaki 24 saatlik gösterim sınırı, dosyanın aynı anda fiziksel olarak silindiği anlamına gelmez. Hesap, mesaj ve medya verileri hizmetin çalışması için saklanabilir. Profil → Ayarlar → Hesabı sil üzerinden silmeyi başlatabilirsiniz. İşlem hata verirse başarılı silme olarak değerlendirilmez; tekrar deneyebilir veya destek isteyebilirsiniz. Güvenlik kayıtları ve destek yazışmaları, gerekli olduğu ve uygulanabilir yükümlülükler izin verdiği ölçüde tutulabilir.</p></section>
    <section><h2 className="mb-3 text-2xl font-semibold">Tercihleriniz ve talepleriniz</h2><p>Profilinizi düzenleyebilir, izinleri ve bildirimleri kapatabilir, içerik ve kullanıcıları şikayet edebilir veya engelleyebilirsiniz. Verilerinize erişim, düzeltme veya silme talepleri için <a className="underline" href="mailto:aricefearda@gmail.com">aricefearda@gmail.com</a> adresine yazın. Yaşadığınız yere göre veri koruma haklarınız ve yetkili kuruma başvurma hakkınız bulunabilir.</p></section>
    <section lang="en"><h2 className="mb-3 text-2xl font-semibold">English summary</h2><p>Nool processes account identifiers, email, profile details, uploaded videos and audio, comments, reactions, friendships, group membership, messages and reports. With permission, precise location is used for nearby content and video placement. Supabase provides authentication, storage and database services; Firebase may provide notifications. Content can be linked to your account. A 24-hour feed window does not guarantee physical file deletion. You can initiate account deletion in Profile → Settings → Delete account. For support or privacy requests, email aricefearda@gmail.com.</p></section>
    <p><a className="text-amber-300 underline" href="https://drective.io">https://drective.io</a></p>
  </article></main>;
}
